name: Deploy Tasky to EKS

on:
  push:
    branches:
      - main
    paths:
      - 'k8s/**'
      - '.github/workflows/k8s-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-2 --name wiz-eks-cluster-v6

      - name: Deploy Tasky manifests to EKS
        run: |
          kubectl apply -f k8s/serviceaccount.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Wait for pod to start
        run: sleep 30

      - name: Get pods
        run: kubectl get pods

      - name: Print logs for tasky pod
        run: |
          POD=$(kubectl get pods -l app=tasky -o jsonpath="{.items[0].metadata.name}")
          kubectl logs $POD

      - name: Check cluster-admin access for tasky-admin
        run: |
          kubectl auth can-i '*' '*' --as=system:serviceaccount:default:tasky-admin

          
      - name: Force rollout of Tasky deployment
        run: |
          kubectl rollout restart deployment tasky
