name: Deploy to EKS

on:
  push:
    branches:
      - main
    paths:
      - 'k8s/**'
      - '.github/workflows/k8s-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Install kubectl
        uses: aws-actions/setup-kubectl@v2
        with:
          version: '1.29'

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-2 --name wiz-eks-cluster-v5

      - name: Deploy Tasky to EKS
        run: |
          kubectl apply -f k8s/serviceaccount.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
